# Generated by Django 3.0.7 on 2020-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('convenience_goods', 'Convenience Goods'), ('shopping_goods', 'Shopping Goods'), ('specialty_goods', 'Specialty Goods')], max_length=125),
        ),
        migrations.AlterField(
            model_name='products',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='products/files/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='detailed_view_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_new',
            field=models.BinaryField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='products',
            name='production_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
